// all the key strings used by settings from all classes and features
// collected in one place to make search and config simpler
public class zak_Keys {

    // use cache-partition to assign partition to use caching for record types and profiles.
    // it should be fully specified name of the partitiion, like: local.zak
    public static final String SETTINGS_CACHE_PARTITION = 'cache-partition';

    // set cache-profiles to comma separated list of profile names which should be cached at once
    public static final String SETTINGS_CACHE_PROFILES = 'cache-profiles';


}